{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"DimCity\",\"DimCustomer\",\"DimStockItem\",\"FactSale\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.124.1805.0 (23.12)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "3171326a-4278-4a40-99a9-a31fb6ce57a0",
        "fromColumn": "Customer Key",
        "fromTable": "FactSale",
        "toColumn": "Customer Key",
        "toTable": "DimCustomer"
      },
      {
        "name": "a1bf0d3e-eda5-446b-a899-a7030e33f0b4",
        "fromColumn": "Stock Item Key",
        "fromTable": "FactSale",
        "toColumn": "Stock Item Key",
        "toTable": "DimStockItem"
      },
      {
        "name": "328c862e-6351-45b0-aadb-77c88f580be2",
        "fromColumn": "City Key",
        "fromTable": "FactSale",
        "toColumn": "City Key",
        "toTable": "DimCity"
      },
      {
        "name": "374d02bd-6f1d-4bb8-bf5d-cc9a919f4084",
        "fromColumn": "Delivery Date Key",
        "fromTable": "FactSale",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_39520679-b51d-4306-863a-042aa85f0500"
      },
      {
        "name": "ce1e9054-37f9-488b-94a6-bcc1dbb4e139",
        "fromColumn": "Invoice Date Key",
        "fromTable": "FactSale",
        "toColumn": "Date",
        "toTable": "DimDate"
      }
    ],
    "sourceQueryCulture": "sv-SE",
    "tables": [
      {
        "name": "DimCity",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7e4ed770-adcf-491d-9d79-37a61bc2d4bc",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "9f44c0e1-0dc9-4480-94ba-549a50be9b4c",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "State Province",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "StateOrProvince",
            "dataType": "string",
            "lineageTag": "9166a4fe-48cc-46e9-a829-55ee008b6aad",
            "sourceColumn": "State Province",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "County",
            "dataType": "string",
            "lineageTag": "99ca04cd-3aae-46a4-a9be-89e451d677bd",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Territory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d79963c-4eb5-4ebf-9c13-37e3453f8502",
            "sourceColumn": "Sales Territory",
            "summarizeBy": "none"
          },
          {
            "name": "Latest Recorded Population",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8871d8cd-b1a2-4b80-8f2a-b7c8d93761ec",
            "sourceColumn": "Latest Recorded Population",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "18a9cf40-3462-47a9-8483-ec6b279292c3",
        "partitions": [
          {
            "name": "DimCity",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/DavidThorzen/ssbi/main/WWI/DimCity.csv\"),[Delimiter=\",\", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"City Key\", Int64.Type}, {\"City\", type text}, {\"State Province\", type text}, {\"Country\", type text}, {\"Sales Territory\", type text}, {\"Location\", type text}, {\"Latest Recorded Population\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Location\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_285af4d1-0fd8-4c1c-b8ac-156e9f2e16be",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7426fb00-bb67-47f4-9602-3bdcfa1b1dcc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "9af62b8b-a14f-4ecc-a46b-36af91cad515",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "b9cde09e-2d37-4945-b711-5c6c6a6f9c44",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0b9d4fda-0465-495a-ba23-062f0f7ff31b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "266a4532-ece3-497b-9e35-ae4a37dbaaa2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "31c0c2e1-3c1e-4bed-8432-ef35aa8930fe",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6cb645bc-c61b-43b5-b849-0666f4420b0f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "9ef2c035-bf99-4dd9-a2c8-3121dcfa1178",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "633ec9a7-c70b-4a20-89b1-6aee1d2cf28f",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "140eb8fd-b1cb-4535-a6b1-047c5c749d4b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "0bd983f0-570c-4402-a6d3-9fa158d001a8",
                "ordinal": 3
              }
            ],
            "lineageTag": "34ca7ca2-bcbe-4ff1-a802-fd6a0f716382"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "95ba0afb-57fd-4d3d-8c96-1f57f054993e",
        "partitions": [
          {
            "name": "DateTableTemplate_285af4d1-0fd8-4c1c-b8ac-156e9f2e16be",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "DimCustomer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "392f4ebc-4aea-4f53-bd95-4e1cbf2c6f8c",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "6b8b821d-8157-437e-9b9d-d899921b8835",
            "sourceColumn": "WWI Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "141b0033-a148-4abf-9ed6-a86ea16aaaa9",
            "sourceColumn": "Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Bill To Customer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84c72a14-48d5-4125-904b-9d42f19f0d8e",
            "sourceColumn": "Bill To Customer",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "356b3ddf-dbbe-4540-9b41-a33cfba0911a",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Group",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b780153-c882-43ca-9dba-af65157b87d0",
            "sourceColumn": "Buying Group",
            "summarizeBy": "none"
          },
          {
            "name": "Primary Contact",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "94d22033-21a5-40fe-8824-8b47321d22ed",
            "sourceColumn": "Primary Contact",
            "summarizeBy": "none"
          },
          {
            "name": "Postal Code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4892a43-5d12-492c-aa19-41b0c3bd9854",
            "sourceColumn": "Postal Code",
            "summarizeBy": "none"
          },
          {
            "name": "Credit Limit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c179194c-fbd6-4faf-9e3e-bbe50fd82419",
            "sourceColumn": "Credit Limit",
            "summarizeBy": "none"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7c5967f1-8ce9-41fd-8edf-45c8d74f8aea",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "59d5217c-c6f1-4adf-9827-7c600ed48cd7",
        "partitions": [
          {
            "name": "DimCustomer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/DavidThorzen/ssbi/main/WWI/DimCustomer.csv\"),[Delimiter=\",\", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [Column2] <> \"\"),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Filtered Rows\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Customer Key\", Int64.Type}, {\"WWI Customer ID\", Int64.Type}, {\"Customer\", type text}, {\"Bill To Customer\", type text}, {\"Category\", type text}, {\"Buying Group\", type text}, {\"Primary Contact\", type text}, {\"Postal Code\", type text}, {\"Credit Limit\", type text}, {\"Valid From\", type text}, {\"Valid To\", type text}, {\"Lineage Key\", Int64.Type}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Valid To\", \"Valid From\"}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Removed Columns\",\"?\",\"\",Replacer.ReplaceText,{\"Credit Limit\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\",\",\"\",Replacer.ReplaceText,{\"Credit Limit\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\".\",\",\",Replacer.ReplaceText,{\"Credit Limit\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\"-\",\"\",Replacer.ReplaceText,{\"Credit Limit\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value3\",{{\"Credit Limit\", type number}})",
                "in",
                "    #\"Changed Type2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimStockItem",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "50a12433-2e5a-4a54-85c5-cd65d355b401",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Stock Item ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2df5e660-4754-4794-a6a9-a3f9315c83a6",
            "sourceColumn": "WWI Stock Item ID",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ed063dd-7550-413c-8c41-0502f0a6407d",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f8a86fdd-453c-4873-a629-060349a5d4a4",
            "sourceColumn": "Color",
            "summarizeBy": "none"
          },
          {
            "name": "Selling Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6c9a464-1009-4d46-8fb3-042b5d096545",
            "sourceColumn": "Selling Package",
            "summarizeBy": "none"
          },
          {
            "name": "Buying Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "240d5dbf-d20c-4a4e-b582-90e0a0d081dd",
            "sourceColumn": "Buying Package",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8082cdec-8d40-4562-9f3c-1e9b85f557a5",
            "sourceColumn": "Brand",
            "summarizeBy": "none"
          },
          {
            "name": "Size",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb9ad58b-0549-4857-9f44-db791a5e0aff",
            "sourceColumn": "Size",
            "summarizeBy": "none"
          },
          {
            "name": "Lead Time Days",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30da0984-f268-42ea-93f7-e65b400c8048",
            "sourceColumn": "Lead Time Days",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity Per Outer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f16a350-f5cb-4511-8ed4-1381c8066b8d",
            "sourceColumn": "Quantity Per Outer",
            "summarizeBy": "none"
          },
          {
            "name": "Is Chiller Stock",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8478557d-877b-4aea-8547-6c9a621a6fad",
            "sourceColumn": "Is Chiller Stock",
            "summarizeBy": "none"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3f2117d9-aac9-47ec-bf7d-eca260244a33",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "none"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4724108e-eada-442a-ad1a-7cbce5ed2d49",
            "sourceColumn": "Unit Price",
            "summarizeBy": "none"
          },
          {
            "name": "Recommended Retail Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0afe94dc-d073-490d-9121-8ee388e46dcb",
            "sourceColumn": "Recommended Retail Price",
            "summarizeBy": "none"
          },
          {
            "name": "Typical Weight Per Unit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a89e5f3f-1479-4984-a87b-0e16adc48cb3",
            "sourceColumn": "Typical Weight Per Unit",
            "summarizeBy": "none"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e67b500c-77d9-45bd-b64e-c8e6b41bc577",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "c36208ee-b8da-48b3-92d5-c8a5569ca1c5",
        "partitions": [
          {
            "name": "DimStockItem",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/DavidThorzen/ssbi/main/WWI/DimStockItem.csv\"),[Delimiter=\",\", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}}),",
                "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each [Column2] <> \"\"),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(#\"Filtered Rows\", [PromoteAllScalars=true]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Stock Item Key\", Int64.Type}, {\"WWI Stock Item ID\", Int64.Type}, {\"Stock Item\", type text}, {\"Color\", type text}, {\"Selling Package\", type text}, {\"Buying Package\", type text}, {\"Brand\", type text}, {\"Size\", type text}, {\"Lead Time Days\", Int64.Type}, {\"Quantity Per Outer\", Int64.Type}, {\"Is Chiller Stock\", Int64.Type}, {\"Barcode\", type text}, {\"Tax Rate\", Int64.Type}, {\"Unit Price\", type text}, {\"Recommended Retail Price\", type text}, {\"Typical Weight Per Unit\", type text}, {\"Photo\", type text}, {\"Discount\", type text}, {\"Valid From\", type text}, {\"Valid To\", type text}, {\"Lineage Key\", Int64.Type}}),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Changed Type1\",\"N/A\",\"\",Replacer.ReplaceText,{\"Color\", \"Brand\"}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Replaced Value\",{\"Valid From\", \"Valid To\", \"Discount\", \"Photo\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Removed Columns\",\"N/A\",\"\",Replacer.ReplaceText,{\"Barcode\"}),",
                "    #\"Replaced Value2\" = Table.ReplaceValue(#\"Replaced Value1\",\"? \",\"\",Replacer.ReplaceText,{\"Recommended Retail Price\"}),",
                "    #\"Replaced Value3\" = Table.ReplaceValue(#\"Replaced Value2\",\".\",\",\",Replacer.ReplaceText,{\"Recommended Retail Price\"}),",
                "    #\"Replaced Value4\" = Table.ReplaceValue(#\"Replaced Value3\",\".\",\",\",Replacer.ReplaceText,{\"Typical Weight Per Unit\"}),",
                "    #\"Replaced Value5\" = Table.ReplaceValue(#\"Replaced Value4\",\".\",\",\",Replacer.ReplaceText,{\"Unit Price\"}),",
                "    #\"Changed Type2\" = Table.TransformColumnTypes(#\"Replaced Value5\",{{\"Typical Weight Per Unit\", type number}}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Changed Type2\",{\"Barcode\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns1\",{{\"Stock Item\", \"Name\"}}),",
                "    #\"Replaced Value6\" = Table.ReplaceValue(#\"Renamed Columns\",\"\",\"Saknas\",Replacer.ReplaceValue,{\"Color\"})",
                "in",
                "    #\"Replaced Value6\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "FactSale",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "IsHidden"
          }
        ],
        "columns": [
          {
            "name": "Sale Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "277ccf28-a729-4b08-a70a-77ea8e727f6c",
            "sourceColumn": "Sale Key",
            "summarizeBy": "none"
          },
          {
            "name": "City Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "f1590482-cb33-43aa-9e7e-a528fc1db549",
            "sourceColumn": "City Key",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "29c5951c-fc5a-4b7a-b478-b2aba470ad5c",
            "sourceColumn": "Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Bill To Customer Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "82a72af7-0fdb-4205-8672-580a535827bc",
            "sourceColumn": "Bill To Customer Key",
            "summarizeBy": "none"
          },
          {
            "name": "Stock Item Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "67589859-adfa-49c7-bff2-deff8e604166",
            "sourceColumn": "Stock Item Key",
            "summarizeBy": "none"
          },
          {
            "name": "Invoice Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "d072574a-f65c-401f-a031-fc1d1b677757",
            "sourceColumn": "Invoice Date Key",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Date Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "isHidden": true,
            "lineageTag": "4bf96845-3bfe-4af6-8e99-4c2ffd8525f6",
            "sourceColumn": "Delivery Date Key",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_39520679-b51d-4306-863a-042aa85f0500"
                },
                "isDefault": true,
                "relationship": "374d02bd-6f1d-4bb8-bf5d-cc9a919f4084"
              }
            ]
          },
          {
            "name": "Salesperson Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "633ef1e4-e804-46a9-8806-337c3e4c00ce",
            "sourceColumn": "Salesperson Key",
            "summarizeBy": "none"
          },
          {
            "name": "WWI Invoice ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "7219e790-4ce5-4711-991c-9d9dc9fe96fd",
            "sourceColumn": "WWI Invoice ID",
            "summarizeBy": "none"
          },
          {
            "name": "Description",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "629ff6ce-d3e6-4995-92ce-fc0af9c8be9f",
            "sourceColumn": "Description",
            "summarizeBy": "none"
          },
          {
            "name": "Package",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "string",
            "isHidden": true,
            "lineageTag": "4a47d67c-eda2-4ccd-aba5-c7d12fac2265",
            "sourceColumn": "Package",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "a309e569-93f1-427f-b09b-ba6fa7e1fc92",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "c3d6cf98-99a5-47c0-ad9d-e14f823707ec",
            "sourceColumn": "Unit Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "#,0",
            "isHidden": true,
            "lineageTag": "3797a939-9f0c-4fd6-ae06-be7bc32d65ba",
            "sourceColumn": "Tax Rate",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Excluding Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"sv-SE\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"kr\";-#,0.00\\ \"kr\";#,0.00\\ \"kr\"",
            "isHidden": true,
            "lineageTag": "52a2b5c5-cd1c-491c-8bbf-95c98271f540",
            "sourceColumn": "Total Excluding Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Tax Amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "214e1334-ab07-4d5b-b629-18c03351b468",
            "sourceColumn": "Tax Amount",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "isHidden": true,
            "lineageTag": "afe47a7e-4104-426f-8a98-8d071f98f18e",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Including Tax",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"sv-SE\"}"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "double",
            "formatString": "#,0.00\\ \"kr\";-#,0.00\\ \"kr\";#,0.00\\ \"kr\"",
            "isHidden": true,
            "lineageTag": "ee90e093-35fd-44f2-a2e9-a5e3319fbf22",
            "sourceColumn": "Total Including Tax",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Dry Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fc548fd8-5e7b-4b63-abb5-50b2bb9148bf",
            "sourceColumn": "Total Dry Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Total Chiller Items",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a4727f73-f101-45bf-8b4a-633548b8d38b",
            "sourceColumn": "Total Chiller Items",
            "summarizeBy": "sum"
          },
          {
            "name": "Lineage Key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0f5cb6e3-3cdc-40f5-9399-bc2766ec8b87",
            "sourceColumn": "Lineage Key",
            "summarizeBy": "count"
          }
        ],
        "lineageTag": "1130ae7d-1eb8-4970-950b-f895e1fcd0bf",
        "measures": [
          {
            "name": "Qty",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "sum(FactSale[Quantity])",
            "formatString": "0",
            "lineageTag": "6dfe2ac9-f90a-43cd-8a5f-82c75c609e9b"
          },
          {
            "name": "Qty LY",
            "changedProperties": [
              {
                "property": "IsHidden"
              }
            ],
            "expression": "CALCULATE([Qty], DATEADD(DimDate[Date], -1, YEAR))",
            "formatString": "0",
            "lineageTag": "595985a4-5abd-41b9-8232-4e50781cd015"
          },
          {
            "name": "Sum Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(sum(FactSale[Total Including Tax]))",
            "lineageTag": "384027e4-4ddd-49b5-91c0-2fc206c113dd"
          }
        ],
        "partitions": [
          {
            "name": "FactSale",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(Web.Contents(\"https://raw.githubusercontent.com/DavidThorzen/ssbi/main/WWI/FactSale.csv\"),[Delimiter=\",\", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Replaced Value\" = Table.ReplaceValue(#\"Promoted Headers\",\".\",\",\",Replacer.ReplaceText,{\"Quantity\", \"Unit Price\", \"Tax Rate\", \"Total Excluding Tax\", \"Tax Amount\", \"Profit\", \"Total Including Tax\", \"Total Dry Items\", \"Total Chiller Items\", \"Lineage Key\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value\",{{\"Total Including Tax\", type number}, {\"Profit\", type number}, {\"Tax Amount\", type number}, {\"Total Excluding Tax\", type number}, {\"Tax Rate\", Int64.Type}, {\"Unit Price\", type number}, {\"Quantity\", Int64.Type}, {\"Total Dry Items\", Int64.Type}, {\"Total Chiller Items\", Int64.Type}, {\"Invoice Date Key\", type date}, {\"Delivery Date Key\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Quantity\", \"Quantity\"}}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Renamed Columns\",{{\"Lineage Key\", Int64.Type}})",
                "in",
                "    #\"Changed Type1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_39520679-b51d-4306-863a-042aa85f0500",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6cb35a9c-6206-4f0f-87f7-dd4625faf72a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "8c916193-f47c-46e4-8d12-835d9629b821",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "13cf68d0-93b7-47d8-b7ae-31bc3c7a65a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2c15c203-63d0-4472-be79-8553d7d58ba2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "2a72964d-eb75-4ada-ad4b-27e5d45c993f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "beea0ac5-58e1-426b-b9a0-208f0fd46126",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "417f5e38-db08-4b87-ad67-3da0810bec41",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0675bc0d-2ad9-493d-91da-a28109dcfe0a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "b9881ff6-4d0f-4a77-8c88-d93930c0cad2",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c01e316d-efec-4bcd-833f-4753b89b0d2e",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "475409f7-ce8f-4492-a3ac-d4ed9f6d7e91",
                "ordinal": 3
              }
            ],
            "lineageTag": "8c8d963b-b1f2-4900-b7be-c17bd04d7fce"
          }
        ],
        "isHidden": true,
        "lineageTag": "80f66787-ec29-47d5-af77-27408682c755",
        "partitions": [
          {
            "name": "LocalDateTable_39520679-b51d-4306-863a-042aa85f0500",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('FactSale'[Delivery Date Key])), 1, 1), Date(Year(MAX('FactSale'[Delivery Date Key])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dba4c6e97ac34423b227855db9c88061"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isKey": true,
            "isNameInferred": true,
            "lineageTag": "2684f44b-7202-4388-a1fb-e94f73def8db",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "YEAR(DimDate[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "b19cc2b2-fcf2-4055-96db-bcad04b111d3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "MONTH(DimDate[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "0a57a783-3bdf-459b-94f3-5f8400c4e78e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DAY(DimDate[Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "5bb0f1e2-5194-4cbb-842c-5651c4dfb8bb",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"W\"&FORMAT(DimDate[Date], \"ww\")",
            "isDataTypeInferred": true,
            "lineageTag": "ea5606f6-737c-47b4-967d-83685bd48f6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(DimDate[Date], \"mmm\")",
            "isDataTypeInferred": true,
            "lineageTag": "e178345b-bd51-4275-b323-cc346b76981e",
            "sortByColumn": "MonthNum",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Weekday",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT(DimDate[Date], \"ddd\")",
            "isDataTypeInferred": true,
            "lineageTag": "d33eed28-2e17-437e-b030-a7023d6c2abd",
            "sortByColumn": "WeekdayNum",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "WeekdayNum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "WEEKDAY(DimDate[Date], 2)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6b518bc4-2716-4cd9-acc4-e2184b9876ab",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "dataCategory": "Time",
        "hierarchies": [
          {
            "name": "Date YMD",
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "0dcf00e4-8bc1-4f1a-94cf-b4dcece10f3a",
                "ordinal": 0
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "8c9db238-e4ac-4f43-8ebd-5ebee5b3efca",
                "ordinal": 1
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b14038e9-7e7f-4677-80bd-c9a17ad59050",
                "ordinal": 2
              }
            ],
            "lineageTag": "65dabc47-1346-4b15-9833-801a835b4317"
          }
        ],
        "lineageTag": "7c6dcc88-e2cb-4856-bc80-161d394a9a1b",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": "CALENDAR(min(FactSale[Invoice Date Key]), max(FactSale[Invoice Date Key]))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}